#cloud-config

users:
  - default
  - name: rainpole
    primary_group: rainpole
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, wheel
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
    - <public_key>