#cloud-config

chpasswd: 
    list: |
      devops:1
    expire: false
users:
  - default 
  - name: devops
    gecos: Devops
    lock_passwd: false
    groups: sudo, users, admin, wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
system_info: 
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]

disable_root: true #Enable root acce
ssh_pwauth: yes #Use pwd to access (otherwise follow official doc to use ssh-keys)

package_upgrade: false

packages:
  - jq

resize_rootfs: true

runcmd:
  - [ sgdisk, -e, "/dev/sda" ]
  - [ partprobe ]
  - [ parted, -s, "/dev/sda", resizepart, 3, "100%" ]
  - [ growpart, "/dev/sda", 3 ] 
  - [ pvresize, "/dev/sda3" ] # Resize the physical volume
  - [ lvextend, -l, "+100%FREE", "/dev/mapper/rhel-root" ] # Extend the logical volume
  - [ xfs_growfs , "/dev/mapper/rhel-root" ] # Grow the XFS filesystem

growpart:
  mode: auto
  devices: ["/dev/sda", 3]
  ignore_growroot_disabled: false