#cloud-config

chpasswd:
  list: |
    devops:1
  expire: false
users:
  - default
  - name: devops
    gecos: Devops
    lock_passwd: false
    groups: sudo, users, admin, wheel
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
system_info:
  default_user:
    name: devops
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]

disable_root: true #Enable root acce
ssh_pwauth: yes #Use pwd to access (otherwise follow official doc to use ssh-keys)

package_upgrade: false

packages:
  # - git
  # - apt-transport-https
  - jq

resize_rootfs: true

runcmd:
  - [sgdisk, -e, "/dev/sda"]
  - [partprobe]
  - [parted, -s, "/dev/sda", resizepart, 3, "100%"]
  - [growpart, "/dev/sda", 3]
  - [pvresize, "/dev/sda3"] # Resize the physical volume
  - [lvextend, -l, "+100%FREE", "/dev/mapper/rhel-root"] # Extend the logical volume
  - [xfs_growfs, "/dev/mapper/rhel-root"] # Grow the XFS filesystem
  - [sh, -c, 'echo "10.210.24.205 ddplatform-pvt-registry" | tee -a /etc/hosts']
  - [update-ca-trust]
  - [systemctl, stop, firewalld]
  - [systemctl, disable, firewalld]

write_files:
  - content: |
      -----BEGIN CERTIFICATE-----
      MIIFSTCCAzGgAwIBAgIUXobEAvp4W5JHGNXBTFQB9fW1X+kwDQYJKoZIhvcNAQEL
      BQAwIjEgMB4GA1UEAwwXZGRwbGF0Zm9ybS1wdnQtcmVnaXN0cnkwHhcNMjMxMDE3
      MDU0NTQ0WhcNMzMxMDE0MDU0NTQ0WjAiMSAwHgYDVQQDDBdkZHBsYXRmb3JtLXB2
      dC1yZWdpc3RyeTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALtb7EyD
      8BUxTtFWto+1a6S4VKf1HAOm3LVGR8iFU8sDZRC1KdTrf1GM023D4kjNy5S8wq/8
      uLwSGTxC5rmJ5prjYkAbsg6CTJsZ/D0+56Pc9yevtZGD5BCxrVWqhh4viNDaJZ3p
      JwAyf5Um9qUucp1kayZfcSbSdR7PC2/uMqP2Fd3baCLkidb5F/a9X3YdUXYPMH9w
      LyjwEH3QQqu3oYxq9uI5WaG2yVo0PALElFdl4OLkClQx0fKQ+qLICTD0Wp6FPKbe
      GasSD+HLGcFGm94IxrfM2aH5Oq0WQdE7ux2l7Veswnw0R96IiNzQ4BTI3A+AUih/
      F5DzcxpgB0PQIMVuUxtPDzPw9WC9TyvWETIKXh03WWMNZpRT5ZTIpPwzFt+gabEJ
      CAMdsJAVRJSlEuopEbl0dohG0O1RCzPMW4dZJyVKAIuU6rvvK/EVUAnFOhEXFRkx
      0zbZ49yc7xi/h+8MxdeK+B36BBssV4jPAaDEO/rIzlp7qGBCXZymI/kfOXsPCPGM
      b/qqVPmtD/MFzqv4N3Hst5ft50OWB/a//Krg+OMNNeJRMALcFJQRWAgcPlA8Uebo
      VzWUg5RH9ZxQvZTKTkWRyuZFYyyiRleVrQrlLLDA2wEHzFuPxYKNmGVWcN2MgnT9
      ZEgkNWcmy/yU2o/Y93wzJrK/hnxrS8kFyOFLAgMBAAGjdzB1MB0GA1UdDgQWBBQb
      LplJUSoUY6zSs9mJQE8Y4TePMzAfBgNVHSMEGDAWgBQbLplJUSoUY6zSs9mJQE8Y
      4TePMzAPBgNVHRMBAf8EBTADAQH/MCIGA1UdEQQbMBmCF2RkcGxhdGZvcm0tcHZ0
      LXJlZ2lzdHJ5MA0GCSqGSIb3DQEBCwUAA4ICAQBRMIhIny+cClL3vgbuf9Ay5k/N
      gZ8kxOEvpwYAcDfJxEqN1hBMCrkRogAXrUAQbA19Xnx5HluEIxyF+KVGiOLlzyr8
      YrZPJS8QlHGcmnerrCNAsI1Ls85solNg9wYvN1PPPI6lOofCEb3jftpr2bfq8VER
      +rbuXTqOyUr1INBscSlwzVKFgWHQhXXCMv6acZmL9pHau4lYBd23Ntw/ECHUcJ3A
      yj1rgl8lpwsK0jOeWwKUXqmrZMW3Sk5zT9JKsKkFVNu0tY/E4kbvbIVhmqstIuLA
      k2iGnyoKKLiccoysEkeXkYXz5lL7+3HL4bXLvtjPZBk24elfQu6PdFtsgySyx8QC
      dgd23V2ilvAAwwkMQsBuo8TL+g76tMORuFPvcrV7P1X5MdDwCEt2fHd0YV8v6Kqg
      CR2OJLJRWKDbNeIhUsEQs275PxnSI5bqifvx2wydBq6Z/gu07iXRXbRQZhQ/RLFV
      iu9JX/QtfoHiJ93YtV5PeDu62mbJTT3vGb/nzQLCIHvWqWtU1HQppJpussa2aYrv
      HpKOfE0woGEy0+dJKI0CYaCJPDsrrcmKpzEEJfS2ReGLVuxhYqYkqhSdcDwlzSdn
      ei5gwMCU3GvUw1/qaDl/CY2lnOiluvb4gQP3Y27gH2f/mxhnJvB4+FrC+rgmho+V
      TaomFIP8CKkgq2IbWg==
      -----END CERTIFICATE-----
    path: /etc/pki/ca-trust/source/anchors/ca.crt
    owner: root:root
    permissions: "0644"

growpart:
  mode: auto
  devices: ["/dev/sda", 3]
  ignore_growroot_disabled: false
